name: Daily Forex Rates Scraper

on:
  schedule:
    # Runs at 5:00 PM IST (11:30 AM UTC) Monday to Friday
    - cron: '30 11 * * 1-5'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-forex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run forex scraper
      run: python scripts/forex_scraper.py
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Node.js dependencies
      run: |
        npm init -y
        npm install csv-parser
          
    - name: Generate API endpoints
      run: |
        mkdir -p public/api/month
        node api/forex-data.js
          
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add data/forex_rates.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "Update forex rates [$(date +'%Y-%m-%d')]"
        git push

    - name: Deploy API to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        branch: gh-pages
        clean: true
        