name: Daily Forex Rates Scraper

on:
  schedule:
    # Runs at 10:00 AM IST (4:30 UTC) every day
    - cron: '30 4 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-forex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run forex scraper
      run: python scripts/forex_scraper.py
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add data/forex_rates.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "Update forex rates [$(date +'%Y-%m-%d')]"
        git push
        